export const FORMACIONES = {
  '4-4-2': [
    { numero: 1, rol: 'Arquero', x: 50, y: 94 },
    { numero: 4, rol: 'Lateral Derecho', x: 82, y: 78 },
    { numero: 2, rol: 'Central Derecho', x: 60, y: 80 },
    { numero: 6, rol: 'Central Izquierdo', x: 38, y: 80 },
    { numero: 3, rol: 'Lateral Izquierdo', x: 18, y: 78 },
    { numero: 7, rol: 'Volante por fuera (derecha)', x: 84, y: 56 },
    { numero: 5, rol: 'Volante Central', x: 58, y: 60 },
    { numero: 8, rol: 'Volante Central / Interno', x: 38, y: 60 },
    { numero: 10, rol: 'Volante por izquierda', x: 16, y: 56 },
    { numero: 9, rol: 'Delantero', x: 38, y: 22 },
    { numero: 11, rol: 'Delantero', x: 62, y: 22 },
  ],
  '4-3-3': [
    { numero: 1, rol: 'Arquero', x: 50, y: 94 },
    { numero: 4, rol: 'Lateral Derecho', x: 82, y: 78 },
    { numero: 2, rol: 'Central Derecho', x: 60, y: 80 },
    { numero: 6, rol: 'Central Izquierdo', x: 38, y: 80 },
    { numero: 3, rol: 'Lateral Izquierdo', x: 18, y: 78 },
    { numero: 5, rol: 'Volante Central', x: 50, y: 62 },
    { numero: 8, rol: 'Volante Interno', x: 70, y: 56 },
    { numero: 10, rol: 'Volante Interno / Enganche', x: 30, y: 56 },
    { numero: 7, rol: 'Extremo Derecho', x: 82, y: 24 },
    { numero: 9, rol: 'Delantero Centro', x: 50, y: 16 },
    { numero: 11, rol: 'Extremo Izquierdo', x: 18, y: 24 },
  ],
  '4-3-1-2': [
    { numero: 1, rol: 'Arquero', x: 50, y: 94 },
    { numero: 4, rol: 'Lateral Derecho', x: 82, y: 78 },
    { numero: 2, rol: 'Central Derecho', x: 60, y: 80 },
    { numero: 6, rol: 'Central Izquierdo', x: 38, y: 80 },
    { numero: 3, rol: 'Lateral Izquierdo', x: 18, y: 78 },
    { numero: 5, rol: 'Volante Central', x: 50, y: 64 },
    { numero: 7, rol: 'Volante Interno', x: 72, y: 58 },
    { numero: 8, rol: 'Volante Interno', x: 28, y: 58 },
    { numero: 10, rol: 'Enganche', x: 50, y: 40 },
    { numero: 9, rol: 'Delantero', x: 36, y: 18 },
    { numero: 11, rol: 'Delantero', x: 64, y: 18 },
  ],
  '4-2-3-1': [
    { numero: 1, rol: 'Arquero', x: 50, y: 94 },
    { numero: 4, rol: 'Lateral Derecho', x: 82, y: 78 },
    { numero: 2, rol: 'Central Derecho', x: 60, y: 80 },
    { numero: 6, rol: 'Central Izquierdo', x: 38, y: 80 },
    { numero: 3, rol: 'Lateral Izquierdo', x: 18, y: 78 },
    { numero: 5, rol: 'Volante Central (doble 5)', x: 40, y: 64 },
    { numero: 8, rol: 'Volante Central (doble 5)', x: 60, y: 64 },
    { numero: 7, rol: 'Volante por fuera (derecha)', x: 82, y: 42 },
    { numero: 10, rol: 'Enganche', x: 50, y: 38 },
    { numero: 11, rol: 'Volante por fuera (izquierda)', x: 18, y: 42 },
    { numero: 9, rol: 'Delantero', x: 50, y: 18 },
  ],
  '5-3-2': [
    { numero: 1, rol: 'Arquero', x: 50, y: 94 },
    { numero: 4, rol: 'Carrilero Derecho', x: 86, y: 64 },
    { numero: 2, rol: 'Central por derecha', x: 64, y: 80 },
    { numero: 5, rol: 'Líbero', x: 50, y: 84 },
    { numero: 6, rol: 'Central por izquierda', x: 36, y: 80 },
    { numero: 3, rol: 'Carrilero Izquierdo', x: 14, y: 64 },
    { numero: 7, rol: 'Volante Interno', x: 70, y: 50 },
    { numero: 8, rol: 'Volante Central', x: 50, y: 54 },
    { numero: 10, rol: 'Volante Interno', x: 30, y: 50 },
    { numero: 9, rol: 'Delantero', x: 38, y: 20 },
    { numero: 11, rol: 'Delantero', x: 62, y: 20 },
  ],
  '5-4-1': [
    { numero: 1, rol: 'Arquero', x: 50, y: 94 },
    { numero: 4, rol: 'Carrilero Derecho', x: 86, y: 62 },
    { numero: 2, rol: 'Central por derecha', x: 64, y: 80 },
    { numero: 5, rol: 'Líbero', x: 50, y: 84 },
    { numero: 6, rol: 'Central por izquierda', x: 36, y: 80 },
    { numero: 3, rol: 'Carrilero Izquierdo', x: 14, y: 62 },
    { numero: 7, rol: 'Volante por fuera (derecha)', x: 82, y: 46 },
    { numero: 8, rol: 'Volante Central', x: 60, y: 52 },
    { numero: 10, rol: 'Volante Central', x: 38, y: 52 },
    { numero: 11, rol: 'Volante por fuera (izquierda)', x: 18, y: 46 },
    { numero: 9, rol: 'Delantero', x: 50, y: 18 },
  ],
  '5-2-3': [
    { numero: 1, rol: 'Arquero', x: 50, y: 94 },
    { numero: 4, rol: 'Carrilero Derecho', x: 86, y: 64 },
    { numero: 2, rol: 'Central por derecha', x: 64, y: 80 },
    { numero: 5, rol: 'Líbero', x: 50, y: 84 },
    { numero: 6, rol: 'Central por izquierda', x: 36, y: 80 },
    { numero: 3, rol: 'Carrilero Izquierdo', x: 14, y: 64 },
    { numero: 8, rol: 'Volante Central', x: 60, y: 58 },
    { numero: 10, rol: 'Volante Central', x: 40, y: 58 },
    { numero: 7, rol: 'Extremo Derecho', x: 82, y: 26 },
    { numero: 9, rol: 'Delantero Centro', x: 50, y: 18 },
    { numero: 11, rol: 'Extremo Izquierdo', x: 18, y: 26 },
  ],
  '3-4-3': [
    { numero: 1, rol: 'Arquero', x: 50, y: 94 },
    { numero: 2, rol: 'Central por derecha', x: 64, y: 80 },
    { numero: 5, rol: 'Líbero', x: 50, y: 84 },
    { numero: 6, rol: 'Central por izquierda', x: 36, y: 80 },
    { numero: 4, rol: 'Carrilero Derecho', x: 86, y: 58 },
    { numero: 7, rol: 'Volante Interno', x: 66, y: 56 },
    { numero: 8, rol: 'Volante Interno', x: 34, y: 56 },
    { numero: 3, rol: 'Carrilero Izquierdo', x: 14, y: 58 },
    { numero: 11, rol: 'Delantero por izquierda', x: 30, y: 22 },
    { numero: 9, rol: 'Delantero Centro', x: 50, y: 16 },
    { numero: 10, rol: 'Delantero por derecha', x: 70, y: 22 },
  ],
  '3-4-1-2': [
    { numero: 1, rol: 'Arquero', x: 50, y: 94 },
    { numero: 2, rol: 'Central por derecha', x: 64, y: 80 },
    { numero: 5, rol: 'Líbero', x: 50, y: 84 },
    { numero: 6, rol: 'Central por izquierda', x: 36, y: 80 },
    { numero: 4, rol: 'Carrilero Derecho', x: 86, y: 58 },
    { numero: 7, rol: 'Volante Interno', x: 66, y: 56 },
    { numero: 8, rol: 'Volante Interno', x: 34, y: 56 },
    { numero: 3, rol: 'Carrilero Izquierdo', x: 14, y: 58 },
    { numero: 10, rol: 'Enganche', x: 50, y: 38 },
    { numero: 9, rol: 'Delantero', x: 38, y: 18 },
    { numero: 11, rol: 'Delantero', x: 62, y: 18 },
  ],
}